document.getElementById("urlForm").addEventListener("submit", function (event) {
event.preventDefault();

const url = document.getElementById("url").value;

if (url.trim() !== "") {
    sessionStorage.setItem("url", url);
    
} else {
    sessionStorage.setItem("url", "https://showroom.one-stage.kkstream.io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjE3N2RhODVjLTllZjgtNTVjYS05M2FkLTAyYTMyZjkwZjg2MyIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV9pZCI6IjI5MDY5ZTA0LTAwYTEtNDRhMy1hYjM5LWE1M2U5ZGJlOWUzMCIsInJlc291cmNlX3R5cGUiOiJSRVNPVVJDRV9UWVBFX0xJVkVfRVZFTlQifQ.TPJs6-hyS_0VPd4xg7N8wpkITPbGsq3CnfXRxePp0K0Ymr7o97TC-qO3Q7ie9hIeVNpTy-sbR0z0tHsA3gpunruMbn-uvctjzpJarWQ7HAMKPNJxUjSNa370i-U3X-AdeB13lj7oRvOjLAdOR65ywwBd_8xdAdsOfDNDSlsDtucsyzRLQI4lvESeOEHPevNOyueny8imCod8XCftz7-K7K707dqpcBQ0b3TCKBpdfxgVWtChAvKV9TFqLiyAPXIw3etTDohpAVnhrzo7g507vC_-7UhGWNhggyq1Fm4Wed2KCtYxiqg2aSLhsyFGR6uC_LBIVnSGNgZr90KlOpkZphS2l8pT3taJtYMBKvZKqHXVpGjAPMyasB7pRX6-rzumzeGgsfQpLhFHPM7qWJbQdhc1SCyjSkDVv7FiY7w_z91gTZiOTqguFvl3rMbxJDfltCFgdb_0dtSlhiPdN70R2_9S2G1zNrih0YiVfl81IvciXDyFJjv_xImAzWWqZ3Jodkg-0qriUw_pTZDMuWB5c4UTKtOq5EZatoBbovkkDHzwqshuLfEeqB9LV4GoBrVtsuumO3w5KpkTJ8kPWd4yrip_gk6hPPzUEezxWaMmn5eDauUwtMYCM2rHTSXeA3l0SId2QndHVIUv-HYCgrLk6nOJCoiCYPh2kE0HE2pb7P0");
}
window.location.href = "chatroom.html";
});